#!/usr/bin/env bash
# Create STARTER schema, MySQL users, credentials file, and gsettings defaults.
# Idempotent across image rebuilds when /var/lib/mysql and /usr/local/etc/starter
# live on persistent volumes.
set -euo pipefail

MARKER=/var/lib/mysql/.starter-initialized
CRED_FILE=/usr/local/etc/starter/db-credentials
SCHEMA_DIRS=(
    /usr/local/share/glib-2.0/schemas
    /usr/share/glib-2.0/schemas
)
SKELETON=/usr/local/share/starter/sql/skeleton.sql

mysql_root() {
    mysql --protocol=socket -uroot "$@"
}

wait_for_mysql() {
    local i
    for i in $(seq 1 90); do
        if mysqladmin --protocol=socket -uroot ping --silent 2>/dev/null; then
            return 0
        fi
        sleep 1
    done
    echo "error: mysqld did not become ready" >&2
    return 1
}

rand_pass() {
    openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 20
}

apply_gsettings_override() {
    local host="$1" port="$2" user="$3" pass="$4" dir
    local override_body
    override_body=$(cat <<EOF
[org.starter.core]
db-host='${host}'
db-port=${port}
db-user='${user}'
db-pass='${pass}'
rules-preprocessor='m4 {F}'
EOF
)
    for dir in "${SCHEMA_DIRS[@]}"; do
        mkdir -p "${dir}"
        if [ ! -f "${dir}/org.starter.gschema.xml" ] \
            && [ -f /usr/local/share/glib-2.0/schemas/org.starter.gschema.xml ]; then
            install -m 644 /usr/local/share/glib-2.0/schemas/org.starter.gschema.xml \
                "${dir}/org.starter.gschema.xml"
        fi
        printf '%s\n' "${override_body}" > "${dir}/99_starter-docker.gschema.override"
        chmod 644 "${dir}/99_starter-docker.gschema.override"
        glib-compile-schemas "${dir}"
        chmod 644 "${dir}/gschemas.compiled" 2>/dev/null || true
    done
}

write_credentials() {
    local host="$1" port="$2" writer_user="$3" writer_pass="$4" reader_user="$5" reader_pass="$6"
    local old_umask
    old_umask=$(umask)
    umask 077
    cat > "${CRED_FILE}" <<EOF
# Generated by init-starter-db.sh — starter-core reads the same values via gsettings
DB_HOST=${host}
DB_PORT=${port}
DB_WRITER_USER=${writer_user}
DB_WRITER_PASS=${writer_pass}
DB_READER_USER=${reader_user}
DB_READER_PASS=${reader_pass}
EOF
    umask "${old_umask}"
    chown root:starter "${CRED_FILE}"
    chmod 640 "${CRED_FILE}"
}

set_starter_gsettings() {
    local host="$1" port="$2" user="$3" pass="$4"
    install -d -o starter -g starter -m 700 /home/starter/.config/dconf /home/starter/.cache/dconf || true
    gset() {
        runuser -u starter -- env \
            XDG_DATA_DIRS=/usr/local/share:/usr/share \
            GSETTINGS_SCHEMA_DIR=/usr/share/glib-2.0/schemas \
            HOME=/home/starter \
            dbus-run-session -- gsettings set org.starter.core "$1" "$2" || true
    }
    gset db-host "${host}"
    gset db-port "${port}"
    gset db-user "${user}"
    gset db-pass "${pass}"
    gset rules-preprocessor 'm4 {F}'
}

# Re-apply settings from the persistent credentials file (survives image rebuild).
restore_from_credentials() {
    # shellcheck disable=SC1090
    set -a
    # shellcheck source=/dev/null
    source "${CRED_FILE}"
    set +a

    local host="${DB_HOST:-127.0.0.1}"
    local port="${STARTER_DB_PORT:-${DB_PORT:-3306}}"
    local writer_user="${DB_WRITER_USER:-STWriter}"
    local writer_pass="${DB_WRITER_PASS:?missing DB_WRITER_PASS in ${CRED_FILE}}"
    local reader_user="${DB_READER_USER:-STReader}"
    local reader_pass="${DB_READER_PASS:-}"

    write_credentials "${host}" "${port}" "${writer_user}" "${writer_pass}" \
        "${reader_user}" "${reader_pass}"
    apply_gsettings_override "${host}" "${port}" "${writer_user}" "${writer_pass}"
    set_starter_gsettings "${host}" "${port}" "${writer_user}" "${writer_pass}"
    echo "Restored gsettings from ${CRED_FILE} (db-port=${port})"
}

wait_for_mysql

mysql_root < "${SKELETON}"

if [ -f "${MARKER}" ]; then
    echo "STARTER database already initialized (persistent volume)"
    if [ -f "${CRED_FILE}" ]; then
        restore_from_credentials
    else
        echo "warning: ${CRED_FILE} missing on etc volume; gsettings not restored" >&2
    fi
    exit 0
fi

DB_HOST="${STARTER_DB_HOST:-127.0.0.1}"
DB_PORT="${STARTER_DB_PORT:-3306}"
WRITER_USER="${STARTER_DB_WRITER_USER:-STWriter}"
READER_USER="${STARTER_DB_READER_USER:-STReader}"
WRITER_PASS="${STARTER_DB_WRITER_PASS:-$(rand_pass)}"
READER_PASS="${STARTER_DB_READER_PASS:-$(rand_pass)}"

mysql_root <<EOF
CREATE USER IF NOT EXISTS '${WRITER_USER}'@'%' IDENTIFIED WITH mysql_native_password BY '${WRITER_PASS}';
CREATE USER IF NOT EXISTS '${READER_USER}'@'%' IDENTIFIED WITH mysql_native_password BY '${READER_PASS}';
ALTER USER '${WRITER_USER}'@'%' IDENTIFIED WITH mysql_native_password BY '${WRITER_PASS}';
ALTER USER '${READER_USER}'@'%' IDENTIFIED WITH mysql_native_password BY '${READER_PASS}';
GRANT SELECT, INSERT, UPDATE, DELETE ON STARTER.* TO '${WRITER_USER}'@'%';
GRANT SELECT ON STARTER.* TO '${READER_USER}'@'%';
FLUSH PRIVILEGES;
EOF

write_credentials "${DB_HOST}" "${DB_PORT}" "${WRITER_USER}" "${WRITER_PASS}" "${READER_USER}" "${READER_PASS}"
apply_gsettings_override "${DB_HOST}" "${DB_PORT}" "${WRITER_USER}" "${WRITER_PASS}"
set_starter_gsettings "${DB_HOST}" "${DB_PORT}" "${WRITER_USER}" "${WRITER_PASS}"

touch "${MARKER}"
echo "STARTER database initialized (writer=${WRITER_USER}, reader=${READER_USER})"
echo "Credentials: ${CRED_FILE}"
